### ISSUE TITLE
Clean up fonts and typography in app

### ISSUE THREAD

**Issue by JH1ller** [JH1ller/csgo-stratbook#53]
In the app all font style declarations currently look like this: 

```scss
.class {
  font-family: $font_ubuntu-bold;
  font-size: 1.4rem;
  color: $color--abbey;
}
```

It would be cleaner to refactor this into a set of typography mixins like so:

```scss
@mixin typo_hl5($color: $color--abbey) {
  font-family: $font_ubuntu-bold;
  font-size: 1.4rem;
  color: $color;
}

.class {
   @include typo_hl5($color--white);
}
```
